# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "content_urls"
  s.version = "0.1.10"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dennis Sutch"]
  s.date = "2013-09-28"
  s.description = "Parses various file types (HTML, CSS, JavaScript, ...) for URLs and provides methods for iterating through URLs and changing URLs."
  s.email = "dennis@sutch.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "content_urls.gemspec",
    "lib/content_urls.rb",
    "lib/content_urls/parsers/css_parser.rb",
    "lib/content_urls/parsers/html_parser.rb",
    "lib/content_urls/parsers/java_script_parser.rb",
    "lib/content_urls/version.rb",
    "spec/content_urls_spec.rb",
    "spec/css_parser_spec.rb",
    "spec/html_parser_spec.rb",
    "spec/java_script_parser_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/sutch/content_urls"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.0.7"
  s.summary = "Find and rewrite URLs in different types of content."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.5.10"])
      s.add_runtime_dependency(%q<css_parser>, ["~> 1.3.5"])
      s.add_runtime_dependency(%q<rkelly>, ["~> 1.0.7"])
      s.add_development_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_development_dependency(%q<yard>, ["~> 0.8.7.2"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_development_dependency(%q<rake>, ["~> 10.1.0"])
    else
      s.add_dependency(%q<nokogiri>, ["~> 1.5.10"])
      s.add_dependency(%q<css_parser>, ["~> 1.3.5"])
      s.add_dependency(%q<rkelly>, ["~> 1.0.7"])
      s.add_dependency(%q<rspec>, ["~> 2.14.1"])
      s.add_dependency(%q<yard>, ["~> 0.8.7.2"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.3.5"])
      s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
      s.add_dependency(%q<rake>, ["~> 10.1.0"])
    end
  else
    s.add_dependency(%q<nokogiri>, ["~> 1.5.10"])
    s.add_dependency(%q<css_parser>, ["~> 1.3.5"])
    s.add_dependency(%q<rkelly>, ["~> 1.0.7"])
    s.add_dependency(%q<rspec>, ["~> 2.14.1"])
    s.add_dependency(%q<yard>, ["~> 0.8.7.2"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.3.5"])
    s.add_dependency(%q<jeweler>, ["~> 1.8.7"])
    s.add_dependency(%q<rake>, ["~> 10.1.0"])
  end
end

